// Command openapi-gen turns Canvas OpenAPI metadata into a discoverable CLI catalog.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type document struct {
	Paths      map[string]map[string]yaml.Node `yaml:"paths"`
	Components components                      `yaml:"components"`
	Security   []map[string][]string           `yaml:"security"`
}

type components struct {
	Parameters    map[string]parameter   `yaml:"parameters"`
	RequestBodies map[string]requestBody `yaml:"requestBodies"`
	Responses     map[string]response    `yaml:"responses"`
	Schemas       map[string]schema      `yaml:"schemas"`
}

type operation struct {
	OperationID string                `yaml:"operationId"`
	Summary     string                `yaml:"summary"`
	Description string                `yaml:"description"`
	Tags        []string              `yaml:"tags"`
	Parameters  []parameter           `yaml:"parameters"`
	RequestBody *requestBody          `yaml:"requestBody"`
	Responses   map[string]response   `yaml:"responses"`
	Security    []map[string][]string `yaml:"security"`
	External    externalDocumentation `yaml:"externalDocs"`
}

type externalDocumentation struct {
	URL string `yaml:"url"`
}

type parameter struct {
	Ref         string `yaml:"$ref"`
	Name        string `yaml:"name"`
	In          string `yaml:"in"`
	Required    bool   `yaml:"required"`
	Description string `yaml:"description"`
	Schema      schema `yaml:"schema"`
}

type schema struct {
	Ref         string            `yaml:"$ref"`
	Type        string            `yaml:"type"`
	Format      string            `yaml:"format"`
	Description string            `yaml:"description"`
	Enum        []any             `yaml:"enum"`
	Default     any               `yaml:"default"`
	Items       *schema           `yaml:"items"`
	Properties  map[string]schema `yaml:"properties"`
	Required    []string          `yaml:"required"`
}

type requestBody struct {
	Ref         string               `yaml:"$ref"`
	Required    bool                 `yaml:"required"`
	Description string               `yaml:"description"`
	Content     map[string]mediaType `yaml:"content"`
}

type mediaType struct {
	Schema schema `yaml:"schema"`
}

type response struct {
	Ref         string               `yaml:"$ref"`
	Description string               `yaml:"description"`
	Content     map[string]mediaType `yaml:"content"`
}

type item struct {
	path   string
	method string
	op     operation
	params []parameter
}

func main() {
	specPath := flag.String("spec", "", "OpenAPI YAML file")
	outPath := flag.String("out", "internal/api/generated.go", "generated Go file")
	flag.Parse()
	if *specPath == "" {
		fatal("-spec is required")
	}
	data, err := os.ReadFile(*specPath)
	if err != nil {
		fatal(err.Error())
	}
	var spec document
	if err := yaml.Unmarshal(data, &spec); err != nil {
		fatal(err.Error())
	}

	items := collectOperations(spec)
	var out strings.Builder
	out.WriteString("// Code generated by tools/openapi-gen; DO NOT EDIT.\npackage api\n\nvar GeneratedOperations = []Operation{\n")
	for _, item := range items {
		writeOperation(&out, spec, item)
	}
	out.WriteString("}\n")
	if err := os.WriteFile(*outPath, []byte(out.String()), 0o644); err != nil {
		fatal(err.Error())
	}
}

func collectOperations(spec document) []item {
	var items []item
	for path, fields := range spec.Paths {
		var pathParameters []parameter
		if node, ok := fields["parameters"]; ok {
			_ = node.Decode(&pathParameters)
		}
		for method, node := range fields {
			upper := strings.ToUpper(method)
			if !isHTTPMethod(upper) {
				continue
			}
			var op operation
			if err := node.Decode(&op); err != nil {
				fatal(fmt.Sprintf("decode %s %s: %v", upper, path, err))
			}
			if op.Security == nil {
				op.Security = spec.Security
			}
			params := mergeParameters(spec, pathParameters, op.Parameters)
			items = append(items, item{path: path, method: upper, op: op, params: params})
		}
	}
	sort.Slice(items, func(i, j int) bool {
		left, right := operationID(items[i]), operationID(items[j])
		if left == right {
			return items[i].path+items[i].method < items[j].path+items[j].method
		}
		return left < right
	})
	return items
}

func mergeParameters(spec document, path, operation []parameter) []parameter {
	merged := map[string]parameter{}
	order := make([]string, 0, len(path)+len(operation))
	for _, raw := range append(append([]parameter{}, path...), operation...) {
		p := resolveParameter(spec, raw)
		key := p.In + "\x00" + p.Name
		if _, exists := merged[key]; !exists {
			order = append(order, key)
		}
		merged[key] = p
	}
	result := make([]parameter, 0, len(order))
	for _, key := range order {
		result = append(result, merged[key])
	}
	return result
}

func resolveParameter(spec document, p parameter) parameter {
	const prefix = "#/components/parameters/"
	if strings.HasPrefix(p.Ref, prefix) {
		if resolved, ok := spec.Components.Parameters[strings.TrimPrefix(p.Ref, prefix)]; ok {
			return resolved
		}
	}
	return p
}

func resolveRequestBody(spec document, body *requestBody) *requestBody {
	if body == nil {
		return nil
	}
	const prefix = "#/components/requestBodies/"
	if strings.HasPrefix(body.Ref, prefix) {
		if resolved, ok := spec.Components.RequestBodies[strings.TrimPrefix(body.Ref, prefix)]; ok {
			return &resolved
		}
	}
	return body
}

func writeOperation(out *strings.Builder, spec document, item item) {
	id := operationID(item)
	group := ""
	if len(item.op.Tags) > 0 {
		group = item.op.Tags[0]
	}
	scopes := uniqueScopes(item.op.Security)
	body := resolveRequestBody(spec, item.op.RequestBody)
	params := mergeParameters(spec, item.params, bodyParameters(spec, body))
	fmt.Fprintf(out, "\t{ID: %s, Method: %s, Path: %s, Summary: %s, Description: %s, Group: %s, DocsURL: %s, Scopes: %s, Parameters: %s, RequestBody: %s, Responses: %s},\n",
		quote(id), quote(item.method), quote(item.path), quote(item.op.Summary), quote(clean(item.op.Description)), quote(group), quote(item.op.External.URL), quoteSlice(scopes), quoteParameters(params), quoteRequestBody(body), quoteResponses(spec, item.op.Responses))
}

func bodyParameters(spec document, body *requestBody) []parameter {
	if body == nil {
		return nil
	}
	contentTypes := make([]string, 0, len(body.Content))
	for contentType := range body.Content {
		contentTypes = append(contentTypes, contentType)
	}
	sort.Strings(contentTypes)
	for _, contentType := range contentTypes {
		s := resolveSchema(spec, body.Content[contentType].Schema)
		required := make(map[string]bool, len(s.Required))
		for _, name := range s.Required {
			required[name] = true
		}
		keys := make([]string, 0, len(s.Properties))
		for key := range s.Properties {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		result := make([]parameter, 0, len(keys))
		for _, name := range keys {
			property := resolveSchema(spec, s.Properties[name])
			result = append(result, parameter{Name: name, In: "body", Required: required[name], Description: property.Description, Schema: property})
		}
		if len(result) > 0 {
			return result
		}
	}
	return nil
}

func resolveSchema(spec document, value schema) schema {
	const prefix = "#/components/schemas/"
	if strings.HasPrefix(value.Ref, prefix) {
		if resolved, ok := spec.Components.Schemas[strings.TrimPrefix(value.Ref, prefix)]; ok {
			return resolved
		}
	}
	return value
}

func operationID(item item) string {
	if item.op.OperationID != "" {
		return item.op.OperationID
	}
	return strings.ToLower(item.method) + "_" + strings.Trim(strings.NewReplacer("/", "_", "{", "", "}", "", ":", "").Replace(item.path), "_")
}

func quoteParameters(values []parameter) string {
	if len(values) == 0 {
		return "nil"
	}
	parts := make([]string, 0, len(values))
	for _, p := range values {
		typeName := p.Schema.Type
		if typeName == "array" && p.Schema.Items != nil && p.Schema.Items.Type != "" {
			typeName += "[" + p.Schema.Items.Type + "]"
		}
		if typeName == "" && p.Schema.Ref != "" {
			typeName = strings.TrimPrefix(p.Schema.Ref, "#/components/schemas/")
		}
		parts = append(parts, fmt.Sprintf("{Name: %s, In: %s, Required: %t, Type: %s, Format: %s, Description: %s, Enum: %s, Default: %s}",
			quote(p.Name), quote(p.In), p.Required || p.In == "path", quote(typeName), quote(p.Schema.Format), quote(clean(p.Description)), quoteAnySlice(p.Schema.Enum), quote(valueString(p.Schema.Default))))
	}
	return "[]Parameter{" + strings.Join(parts, ", ") + "}"
}

func quoteRequestBody(body *requestBody) string {
	if body == nil {
		return "nil"
	}
	return fmt.Sprintf("&RequestBody{Required: %t, Description: %s, ContentTypes: %s}", body.Required, quote(clean(body.Description)), quoteMapKeys(body.Content))
}

func quoteResponses(spec document, values map[string]response) string {
	if len(values) == 0 {
		return "nil"
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		r := resolveResponse(spec, values[key])
		parts = append(parts, fmt.Sprintf("{StatusCode: %s, Description: %s, ContentTypes: %s}", quote(key), quote(clean(r.Description)), quoteMapKeys(r.Content)))
	}
	return "[]Response{" + strings.Join(parts, ", ") + "}"
}

func resolveResponse(spec document, value response) response {
	const prefix = "#/components/responses/"
	if strings.HasPrefix(value.Ref, prefix) {
		if resolved, ok := spec.Components.Responses[strings.TrimPrefix(value.Ref, prefix)]; ok {
			return resolved
		}
	}
	return value
}

func uniqueScopes(security []map[string][]string) []string {
	seen := map[string]bool{}
	var result []string
	for _, requirement := range security {
		for scheme, scopes := range requirement {
			if len(scopes) == 0 {
				scopes = []string{scheme}
			}
			for _, scope := range scopes {
				if !seen[scope] {
					seen[scope] = true
					result = append(result, scope)
				}
			}
		}
	}
	sort.Strings(result)
	return result
}

func quoteMapKeys[T any](values map[string]T) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return quoteSlice(keys)
}

func quoteAnySlice(values []any) string {
	stringsOut := make([]string, len(values))
	for i, value := range values {
		stringsOut[i] = valueString(value)
	}
	return quoteSlice(stringsOut)
}

func valueString(value any) string {
	if value == nil {
		return ""
	}
	return fmt.Sprint(value)
}

func clean(value string) string { return strings.Join(strings.Fields(value), " ") }
func quote(value string) string { return strconv.Quote(value) }

func quoteSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = quote(value)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func isHTTPMethod(value string) bool {
	switch value {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
		return true
	default:
		return false
	}
}

func fatal(message string) {
	fmt.Fprintln(os.Stderr, "openapi-gen:", message)
	os.Exit(1)
}
